analysis/urls.py
from django.urls import path
from . import views

app_name = "analysis"

urlpatterns = [
    path('analysis', views.show_analysis, name='analysis'),
    path('loading', views.loading, name='loading'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import index.views
import topic.views
import voice.views
import analysis.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index.views.index, name='index'),
    path('topic/', include('topic.urls')),
    path('analysis/', include('analysis.urls')),
    path('voice/', include('voice.urls')),
]

topic/urls.py
from django.urls import path
from . import views

app_name = "topic"

urlpatterns = [
    path('', views.show_topic, name='topic'),
]

voice/urls.py
from django.urls import path
from . import views

app_name = "voice"

urlpatterns = [
    path('', views.get_voice, name='voice'),
]

analysis/models.py
from django.db import models

# Create your models here.

index/models.py
from django.db import models

# Create your models here.

topic/models.py
from django.db import models

# class BigTopic(models.Model):
#     id = models.BigAutoField(help_text="BigTopic ID", primary_key=True)
#     bigTopic = models.CharField(max_length=20, blank=False, null=False)
#
# class SmallTopic(models.Model):
#     id = models.BigAutoField(help_text="SmallTopic ID", primary_key=True)
#     smallTopic = models.ManyToManyField('BigTopic',blank=False)

class Question(models.Model):
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

voice/models.py
from django.db import models

# Create your models here.

analysis/views.py
from django.shortcuts import render
import subprocess
from django.http import HttpResponse
import datetime
import os.path
from analysis.voice_ml import run_ml

def loading(request):
    return render(request, 'loading.html')

def show_analysis(request):
    filename = 'voice'
    saved_file_path = convert_voice(filename)
    # print("saved_file_path: {}".format(saved_file_path))
    error_handle_code = saved_file_path.get('code')

    if error_handle_code == 999:
        text = saved_file_path.get('message')
        data = [0, 0, 0, 0]
        return render(request, 'show_anaylsis.html', {'text': text,})
    else:
        # saved_file_path = "C:\\Users\\iykim\\Downloads\\voice.wav"
        file_path = saved_file_path.get('message')
        result = get_file(file_path)

        # print("file result: {}".format(result))
        error_handle_code = result.get('code')

        if error_handle_code == 999:
            text = result.get('message')
            data = [0, 0, 0, 0]

        elif error_handle_code == 200:
            result = result.get('message')
            # print(result)
            text = result.get('text')
            data = result.get('data')
            return render(request, 'show_anaylsis.html', {'text': text, "data" : data})


# convert oga to wav
def convert_voice(filename):
    #TODO when save voice file, user can write filename and goodtalker get filename to use convert wav name
    # src_f = "C:\\Users\\사용자 이름\\Downloads\\{}.oga".format(filename)
    # dst_f = "C:\\Users\\사용자 이름\\Downloads\\{}.wav".format(filename)
    src_f = "C:\\Users\\iykim\\Downloads\\{}.oga".format(filename)
    dst_f = "C:\\Users\\iykim\\Downloads\\{}.wav".format(filename)

    # print("src_f: {}".format(src_f))

    # print("os.path.isfile(dst_f): {}".format(os.path.isfile(dst_f)))
    if os.path.isfile(src_f) == False:
        res = {"code": 999, "message": "NOT VOICE FILE"}
        return res

    if os.path.exists(dst_f):
        os.remove(dst_f)
        res = {"code": 999, "message": "DST FILE EXISIT"}
        return res
        

    
    # subprocess.run(['ffmpeg.exe 파일 절대경로', '-i', src_f, dst_f])
    subprocess.run(['ffmpeg', '-i', src_f, dst_f])
    # 파일 변환 후 기존 oga 파일 삭제
    os.remove(src_f)
    msg = {"code": 200, "message": str(dst_f)}
    return msg

# get voice.wav file
def get_file(file_path):
    if os.path.isfile(file_path) == False:
        res = {"code": 999, "message": "NOT WAV FILE"}
        return res

    else:
        result = run_ml(file_path)
        res = {"code": 200, "message": result}
        return res

index/views.py
from django.shortcuts import render

def index(request):
    return render(request,'index.html')

topic/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question
from .models import Choice

def show_topic(request):
    topics = Question.objects
    choices = Choice.objects
    # choices_friends = Choice.objects.filter(question_id=1)
    # choices_love = Choice.objects.filter(question_id=3)
    print("topics: {}".format(topics))
    print("choice: {}".format(choices))
    return render(request, 'show_topic.html', {'topics': topics, 'choices': choices})

voice/views.py
from django.shortcuts import render


def get_voice(request):
    return render(request, 'get_voice.html')

analysis/templates/loading.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <title>analysis</title>
    </style>
{% endblock %}

{% block content %}
    loading page...
    </div>
    <div id="loading"></div>
    <div class="btn-nextprev">
        <button class="prev" onclick="location.href='{% url 'topic:topic' %}'">Prev</button>
        <button class="save" onclick="location.href='{% url 'analysis:analysis' %}'">Next</button>
    </div>

{% endblock %}

analysis/templates/show_anaylsis.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <title>analysis</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://smtpjs.com/v3/smtp.js"></script>
    <script type="text/javascript">

      // send Email
      function sendEmail() {
        var inputEmail = prompt('결과를 전송하려면 이메일을 입력하세요!', '');

        if(inputEmail == ""){
          inputEmail = prompt('이메일을 꼭 입력해주세요!', '');
        }
        else{
          Email.send({
              SecureToken : "bbd3d1bf-ced0-4e57-aa16-709c0e26bd55",
              To: inputEmail,
              From: "kiy7833@gmail.com",
              Subject: "Sending Email From GoodTalker",
              Body: "<b> your Text </b> <br> {{text}} <br><br> <b> your Language Habits </b>"
                    + "<br>어: {{ data.0 }}회  <br>아니: {{ data.1 }}회  <br>근데: {{ data.2 }}회 <br>이제: {{data.3}}회",
            })
              .then(function (message) {
                alert(inputEmail+"로 결과를 성공적으로 전송하였습니다 :)")
            });
        }
      }

    </script>
  
{% endblock %}

{% block content %}
    <div class="tit-analysis">
        <span>Your text</span>
        <span>Frequency</span>
      </div>
      <div class="contents-analysis">
          <div class="usertext">
              {{text}}
          </div>
          <div class="frequency">
              <canvas id="myChart"></canvas>
              
          </div>
      </div>
      <div class="btn-nextprev">
          <button class="prev" onclick="location.href='{% url 'topic:topic' %}'">Prev</button>
          <form method = "post">
            <input class="save" type = "button" value = "Send" onclick = "sendEmail()"/>
          </form> 
      </div>

    
    
    <script type="text/javascript">
        // chart
        var ctx = document.getElementById('myChart');
        var myChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: ['어', '아니', '근데', '이제'],
              datasets: [{
                label: '# of Value',
                data: {{data}},
                backgroundColor: [
                    'rgba(255, 99, 132, 0.5)',
                    'rgba(54, 162, 235, 0.5)',
                    'rgba(255, 206, 86, 0.5)',
                    'rgba(75, 192, 192, 0.5)',
                  ],
                  borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                  ],
                  borderWidth: 1
                }]
              },
              options: {
                scales: {
                  yAxes: [{
                    ticks: {
                      beginAtZero: true
                    }
                  }]
                }
              }
        }); 
        
    </script>
{% endblock %}

index/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <title>good talker</title>
    <style>
        .nav-bar p {display: none;}
        </style> 
{% endblock %}

{% block content %}
    <div class="contents-start">
        <img src="{% static 'project/talking.svg' %}">
        <p>원활한 대화 및 자신감을 향상시키기 원하신다면 지금 바로 시작해보세요!</p>
        <button class="btn-start" onclick="location.href='{% url 'topic:topic' %}'">START</button>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'project/style.css' %}">

    <script
      src="https://code.jquery.com/jquery-3.6.0.js"
      integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
      crossorigin="anonymous"></script>
    
    <script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
    {% block header %}

    {% endblock %}
</head>
<body>
    <nav>
        <a href="{% url 'index' %}" class="logo">Good Talker</a>
        <div class="nav-bar">
            <p><a href="{% url 'topic:topic' %}">Topic</a></p>
            <p><a href="{% url 'voice:voice' %}">Voice</a></p>
            <p><a href="{% url 'analysis:analysis' %}">Analysis</a></p>
            <!-- <i class="fas fa-bars fa-lg"></i> -->
        </div>
    </nav>

    <div class="contents">
        {% block content %}


        {% endblock %}
    </div>


</body>
</html>

topic/templates/show_topic.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <title>topic</title>
{% endblock %}

{% block content %}
    <div class="contents-topic">
        <select class="topic-big invisible-scrollbar" name="mainCategory" multiple="multiple">
        </select>

        <i class="fas fa-caret-right"></i>
        <i class="fas fa-caret-down"></i>

        <select class="topic-small invisible-scrollbar" name="subCategory" multiple="multiple">
        </select>
    </div>
    <!--multiple을 쓰면 다 보여주고 없으면 드롭다운으로 선택할 수 있음-->
    <!--키워드로 css select 꾸미기 찾아보면 될듯-->

    <div class="btn-nextprev">
        <button class="prev" onclick="location.href='{% url 'index' %}'">Prev</button>
        <button class="next" onclick="location.href='{% url 'voice:voice' %}'">Next</button>
    </div>

    <script src="{% static 'topic/topic.js' %}" ></script>

{% endblock %}

voice/templates/get_voice.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <title>voice</title>
{% endblock %}   

{% block content %}
    <div class="loading" style="display: none;">
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
    </div>
    <div class="show-voice">
        <div class="contents-upload">
            <div class="upload-record">
                <input type=checkbox id="chk-hear-mic"><label for="chk-hear-mic">마이크 소리 듣기</label>
                <button id="record">녹음</button>
                <button id="stop">정지</button>
                <div id="sound-clips"></div>
            </div>
        </div>
    
        <div class="btn-nextprev">
            <button class="prev" onclick="location.href='{% url 'topic:topic' %}'">Prev</button>
            <button class="next" onclick="loading();location.href='{% url 'analysis:analysis' %}'">Next</button>
        </div>
    </div>
    

    <script src="{% static 'voice/voice.js' %}" ></script>
    <script type="text/javascript">
        function loading(){
            $(".topicSentence").hide();
            $(".show-voice").hide();
            $(".loading").fadeIn("slow");
        }
    </script>
{% endblock %}